apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: war-app-test
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: war-app-test
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.name: war-app-test
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      url: https://github.com/haewons-tanzu/war-app-test
      ref:
        branch: master


